version: "3"
services:
    go:
        build: .
        ports:
            - "8080:8080"

    db:
        image: postgres:latest
        ports:
            - "5432:5432" # random available host port will be chosen, same as -P
        volumes:
            - data-postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=mypass

volumes:
    data-postgres:


