version: "3"
services:
    go:
        image: pgarneau/character_go
        ports:
            - "8080:8080"
        depends_on:
            - migrate

    migrate:
        image: pgarneau/character_migration
        depends_on:
            - db

    db:
        image: postgres:latest
        ports:
            - "5432:5432" # random available host port will be chosen, same as -P
        volumes:
            - db-postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=mypass

volumes:
    db-postgres:


